### ISSUE TITLE
`Gradle Language Server` log Chinese garbled

### ISSUE THREAD

**Issue by mozhuanzuojing** [naco-siren/vscode-gradle-language#17]
Extension Name: Gradle Language Support
Extension Version: 0.2.3
OS Version:window10 21H1
VSCode version:1.62

#### Describe the bug
After the gradle project is initialized, check the `Gradle Language Server` log, there are garbled Chinese characters

#### Screenshots
![image](https://user-images.githubusercontent.com/63572041/137653247-e9c3c929-a393-411b-abb7-63bed9da86e4.png)

#### To Reproduce

git pull https://gitee.com/mozhuanzuojing/java-bug01
Open it by VS Code
wait building
view Gradle Tasks log

#### Expected behavior
Chinese output correctly

**Comment by mozhuanzuojing** [comment]
@ghisvail @nasirjd @naco-siren @tylertian123 Please help to solve this problem.

**Comment by tylertian123** [comment]
The Gradle Language Server is provided by the [Gradle Tasks](https://github.com/microsoft/vscode-gradle) plugin, not this one. I have verified by doing the instructions for reproducing, but there is no Gradle Language Server in the output log. The Gradle Language Server only showed up when I enabled the Gradle Tasks plugin. Please go open an issue in that repository instead.

Also, even with the Gradle Tasks plugin enabled, I still could not reproduce the error. I did a fresh clone and opened it in VS Code, but the output log from Gradle Language Server seems to be completely empty. You might want to check your other extensions.

**Comment by mozhuanzuojing** [comment]
@tylertian123 Thank you very much for your help. I have submitted an issue for the garbled Chinese characters in the Gradle Tasks plugin, and the 3.8.1 version will be fixed soon.
